- .circleci/config.yml
- .circleci/docker/Dockerfile
- .circleci/docker/config/logstash.yml
- .circleci/docker/config/pipelines.yml
- .circleci/docker/pipeline/scalyr.conf
- .circleci/docker_unified_smoke_unit/Dockerfile
- .circleci/docker_unified_smoke_unit/smoketest/smoketest.py
- .circleci/smoketest_logstash.sh
- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- logstash-output-scalyr.gemspec
- spec/logstash/outputs/scalyr_spec.rb
Changes in this PR:
- Change defaults to avoid renaming and adding of fields unless configured, the intent is for users to use Logstash filters to achieve the same effect.
- Update the addEvents format to use log attributes, by default only `logfile` and `serverHost` should be log attributes, with other fields being configurable.
- Switch default compression type to `deflate`.
- Add a `User-Agent` header to requests.
- Copy files necessary to build integration test docker images from the Scalyr Agent repo to here.
> Multitude of changes to prepare for a beta release

- .circleci/docker/Dockerfile
- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/scalyr/common/client.rb
- logstash-output-scalyr.gemspec
A non-`pre` version, `0.1.2` because test uploads used other versions and rubygems.org does accept reuploads of previous versions even if they have been removed.
> Update versions to one that rubygems.org will accept

- lib/logstash/outputs/scalyr.rb
- spec/logstash/outputs/scalyr_spec.rb
Also adds a serverHost value of the actual logstash node to status messages.
> Set default serverHost value when none is present.

- lib/logstash/outputs/scalyr.rb
- spec/logstash/outputs/scalyr_spec.rb
Adding a default parser to any message that passes through the logstash output plugin. The default is being attached to the event and not as a server field since the user would have no way to remove the server field one even if they want to define their own. I have no idea how two parsers on one event would work but its something we want to avoid anyway.
> Add default parser to events

- README.md
- lib/logstash/outputs/scalyr.rb
Documentation was suggesting `agent.eu.scalyr.com` as the endpoint to use for uploading EU logs, but this endpoint doesn't exist. This just changes a comment and the README to reflect the correct `eu.scalyr.com`. Since this is purely a documentation change no release is needed.
> Update README and comment to suggest correct EU scalyr endpoint

- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- spec/logstash/outputs/scalyr_spec.rb
New config option `flush_quantile_estimates_on_status_send` which defaults to false will control if we recreate all the estimators when we sent the status. I'm not sure how these estimators work on the inside so I'm not sure of the effects of observing all the stats for the entire plugin runtime.
This PR also avoids printing the `nil` values the estimators return when there is no data, printing `0` instead.
> Optionally recreate quantile estimators on send, avoid printing `nil`

- CHANGELOG.md
- README.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- logstash-output-scalyr.gemspec
- spec/logstash/outputs/scalyr_spec.rb
This pull request adds support for logging status messages with metrics to stdout in addition to sending this data to Scalyr.
We log those messages using logger INFO level and don't directly print them stdout (we could do that, but I think the convention is to use logger abstraction so log routing and filtering is handled as configured inside logstash config).
This means user may need to configure their logging configuration (https://www.elastic.co/guide/en/logstash/current/logging.html) to ensure log level for the plugin is set to ``INFO``.
This information could be utilized for local monitoring / similar.
> Add support for logging status messages to stdout

- lib/logstash/outputs/scalyr.rb
When enabled the `multi_receive` method will return as quickly as possible. Logstash will think all events have been processed successfully.
> Add option `noop_mode` for debugging

- .circleci/config.yml
- .circleci/docker/config/pipelines.yml
- .circleci/docker/pipeline/scalyr.conf
- .circleci/smoketest_logstash.sh
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- logstash-output-scalyr.gemspec
- spec/logstash/outputs/scalyr_integration_spec.rb
- spec/logstash/outputs/scalyr_spec.rb
The HTTP library seems to be threadsafe to begin with, which leaves only metrics gathering and the SSL certificate error fallback codepath to update. This is as far as I can tell of course, and care should be taken to make sure we look over it all and don't miss anything.
The PRNG is also not threadsafe but it is functional for non-security purposes.
> Update plugin to be thread-safe and support shared concurrency

- README.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- lib/scalyr/constants.rb
- spec/logstash/outputs/scalyr_spec.rb
Small change to include plugin version in the startup + initial status message.
While at it, we should probably also clean up the code and define a constant with version and reference that everywhere where possible instead of copy + paste :D
> Include plugin version in the startup + status message

- Gemfile
- Gemfile.lock
- lib/logstash/outputs/scalyr.rb
- spec/logstash/outputs/scalyr_integration_spec.rb
- spec/logstash/outputs/scalyr_spec.rb
Adds error catching when sending status messages.
Reverts a small testing change that made it in, one log was going to `error` when it should have been going to `debug`.
Adds a quantile metric for how many batches we split `multi_receive` calls into.
Fixes retries, popping the event we want to retry was inside the retry block so it ended up lost on retry.
> Error handling improvements

- lib/logstash/outputs/scalyr.rb
Emit an info level log message after a retry due to error if it succeeds. If the error was logged as debug due to being commonly retried, log success to debug as well.
> Log successful retries

- lib/logstash/outputs/scalyr.rb
Updating of the last send time was done outside of synchronization, which left a window in which could allow a duplicate status to be sent from multiple threads.
> Expand synchronization in `send_status` to avoid duplicate uploads

- CHANGELOG.md
- lib/logstash/outputs/scalyr.rb
- spec/logstash/outputs/scalyr_integration_spec.rb
Also extends existing "Invalid JSON response" body logging to status upload errors.
Not sure if adding more cases for specific errors is the way to approach this. Perhaps a config options for logging error bodies for all errors?
> Log the response body in cases of bad parameters

- CHANGELOG.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- spec/logstash/outputs/scalyr_integration_spec.rb
Adds configurable max retries on error (defaulting to 5). Also by default will send un-uploaded events to the dead letter queue assuming it is configured in logstash.
> Limit retries and support DLQ

- CHANGELOG.md
- Gemfile.lock
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- lib/scalyr/constants.rb
- logstash-output-scalyr.gemspec
- spec/logstash/outputs/scalyr_spec.rb
This pull request includes two changes which should help with client status reporting in case single logstash instance has many conditional scalyr outputs configured out of which most are idle.
It includes two changes:
1. Use a separate short lived client session and connection for initial client status / hello to scalyr server. This way we avoid long lived connection open in case there are no other batches / events send to this instance of the plugin.
2. Only call ``send_status()`` for batches which contain at least one event. This should be fine for as long as plugin instance gets some data, but it will allow us to not reporting status messages with all values being 0 for idle output instances (this can happen because logstash intentionally sends empty batches to plugin sometimes for …
> Client status sending improvements

- .circleci/config.yml
- CHANGELOG.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/util.rb
- spec/benchmarks/bignum_fixing.rb
- spec/logstash/outputs/scalyr_spec.rb
Currently when this is configured to be enabled, it will emit warnings:
`warning: constant ::Bignum is deprecated`
I'm making this off by default for that reason, it might be smart to disable these warnings but I'm unsure.
> Convert bigints to strings to avoid JSON generator errors

- CHANGELOG.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/util.rb
- spec/logstash/outputs/scalyr_spec.rb
- spec/scalyr/common/util_spec.rb
Adds a `flatten_nested_arrays` option that defaults to `true`, controls how we handle arrays during `flatten_nested_values` work. If false we just leave them as is.
Also fixes an issue where any nested flattening below the first level would have the default delimiter, not sure if anyone is relying on that bug but I doubt it.
> Make array flattening optional

- CHANGELOG.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/util.rb
- spec/logstash/outputs/scalyr_spec.rb
- spec/scalyr/common/util_spec.rb
There was a bug fix in the last version that fixed an issue where custom delimiters used in flattening would only affect the first layer of nesting. Unfortunately there was already dashboards and queries that relied on this broken functionality. As a quick fix this PR will reintroduce the bug.
> Reintroduce bug with flattening delimiter

- CHANGELOG.md
- README.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/util.rb
- lib/scalyr/constants.rb
- logstash-output-scalyr.gemspec
- spec/logstash/outputs/scalyr_spec.rb
- spec/scalyr/common/util_spec.rb
Rewrite of the hash/array flattening util code to be iterative, inspired by running into issues related to very deeply nested objects.
I suspect there are multiple ways to make this code nicer, but I was having difficulty keeping these stacks in my head as is (apparently my brain has less memory than what we give this plugin by quite a lot).
> Change flattening code to be iterative and not recursive

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/scalyr/common/util.rb
- lib/scalyr/constants.rb
- logstash-output-scalyr.gemspec
- spec/scalyr/common/util_spec.rb
The iterative flattening code incorrectly handled cases of nested empty collections, resulting in the final key names being all mixed up. This solution causes empty collections to show up as final values which is different from the earlier recursive code, but not necessarily negative.
This PR includes the changes to the Changelog and version for the release that will contain this fix.
> Fix issue with iterative flattening due to empty collections.

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- README.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/constants.rb
- logstash-output-scalyr.gemspec
- spec/logstash/outputs/scalyr_integration_spec.rb
- spec/logstash/outputs/scalyr_spec.rb
This PR adds new quantile metric for tracking the duration of ``build_multi_event_request_array`` method.
Every now and then we see relatively large ``multi_receive_duration_secs`` metric where other metrics are seemingly normal and low (batch not being split into multiple Scalyr requests and serialization and duration metrics being relatively flow).
This may provides us with a better insight if in cases like that, majority of the time is indeed spent in that method.
> Add new metric for tracking the duration of "build_multi_event_request_array" method

- .circleci/config.yml
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/constants.rb
- logstash-output-scalyr.gemspec
- spec/benchmarks/flattening_and_serialization.rb
- spec/benchmarks/json_serialization.rb
- spec/benchmarks/util.rb
- spec/logstash/outputs/scalyr_spec.rb
This PR adds new ``json_library`` config option.
With this config option user can control which library to use for JSON serialization. Valid options are ``stdlib`` and ``jrjackson``.
For now, we default to ``stdlib`` (aka same as before).
Per micro-benchmarks data, ``jrjackson`` can be 2-5x faster than stdlib library - https://app.circleci.com/pipelines/github/scalyr/logstash-output-scalyr/449/workflows/9374afd5-2a00-4fef-8be8-6c0d1f9dc2fd/jobs/1491/parallel-runs/0/steps/0-103.
In the future after more battle testing we may want to consider and switch default value to ``jrjackson`` if no issues are encountered.
> Add support for additional JSON serialization library

- Gemfile
- Gemfile.lock
- spec/logstash/outputs/scalyr_integration_spec.rb
- spec/logstash/outputs/scalyr_spec.rb
- spec/scalyr/common/util_spec.rb
For whatever reason when running a plugin in logstash, the included `json` gem is on version `1.8.6`, well behind the most recent version. This version also still includes the bug where Bignum's are not converted correctly. As a result we want to use this version of `json` when running our tests to confirm our handling of this bug is correct (until we have server side fixes and start using a new json library).
> Use json 1.8.6 in tests, same as the json used when running Logstash

- CHANGELOG.md
- Gemfile.lock
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- lib/scalyr/constants.rb
- logstash-output-scalyr.gemspec
- spec/logstash/outputs/scalyr_integration_spec.rb
- spec/logstash/outputs/scalyr_spec.rb
Small change to the plugin ``register()`` method to handle various errors related to invalid scalyr_server config option value and similar in a more user-friendly manner.
Previously in scenarios like that, plugin would partially mask errors in situations like that which would make it hard to determine the root cause aka why the plugin is not working.
We now throw if the provided error is invalid (e.g. invalid URI string or if we can't resolve the hostname or similar).
> Better handle various errors related to the invalid scalyr server URL in the register() method

- CHANGELOG.md
- lib/logstash/outputs/scalyr.rb
- spec/logstash/outputs/scalyr_integration_spec.rb
- spec/logstash/outputs/scalyr_spec.rb
Small change to increase default number of maximum retries on failure from 5 to 15.
With the previous value of 5, this gave the client a maximum number of 60 seconds of retrying before it gave up and sent messages to DLQ. With this change, the client will now attempt to retry up to 12 minutes (~60 seconds for first 5 retry attempts, then 10 + 60 for subsequent ones) before giving up and sending events to DLQ if all the retry attempts are unsuccessful.
> Increase default number of maximum retries on failure from 5 to 15, change non-fatal error log level from error to warning

- .circleci/docker/pipeline/scalyr.conf
- CHANGELOG.md
- README.md
- lib/logstash/outputs/scalyr.rb
- spec/logstash/outputs/scalyr_spec.rb
This pull request allows users to set  top level``severity`` (sev) field on the DataSet event.
This field contains the event severity / log level and it's special since it's a top level event field (same as ``id``, ``thread`` and ``log`` event attribute) and not part of the event attributes aka ``event.attrs`` field.
To use this functionality, user needs to configure ``severity_field`` plugin config option. This config option tells the plugin which Logstash event field contains the severity value.
For example:
```
output {
scalyr {
api_write_token => 'SCALYR_API_KEY'
...
severity_field => 'severity',
}
}
```
In this example, ``severity`` Logstash event field value carries the severity value. Actual field value must be an integer between 0 to 6 (inclusive), from finest / most verbose to …
> Allow user to specify DataSet event severity field

- .github/workflows/unit_tests.yml
- CHANGELOG.md
- logstash-output-scalyr.gemspec
This pull request updates gemspec metadata so we don't include spec/ directory which contains tests + tests fixtures with the .gem itself - there is no need to include those with the gem (and it slightly reduces the gem size).
> Don't include spec/ directory (tests + tests fixtures) inside the ruby gem

- CHANGELOG.md
- Gemfile
- README.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- lib/scalyr/constants.rb
- logstash-output-scalyr.gemspec
- spec/logstash/outputs/scalyr_integration_spec.rb
Simplest possible solution to get things moving again.
Create a new error class for HTTP response code 413, and if a 413 is returned, raise that error. When PayloadTooLargeError is raised, we skip the normal retry logic and go straight to logging the error, and either sending the request to the DLQ if enabled, or we drop it.
CT-594
> CT-594 Do not retry requests with payloads that are too large

- CHANGELOG.md
- lib/logstash/outputs/scalyr.rb
- spec/logstash/outputs/scalyr_integration_spec.rb
This pull request updates context hash which is included / logged as part of the requests which are retried to also include `total_retries_so_far` and `total_sleep_time_so_far` attributes.
Both of those values can be inferred from existing `will_retry_in_seconds` attribute (since we use fixed delays and back off factor with no jitter), but having direct access makes some queries / searches a bit simpler (and those values can also be graphed directly).
> Update data which is included in the error message context

- CHANGELOG.md
- lib/logstash/outputs/scalyr.rb
- lib/scalyr/common/client.rb
- spec/logstash/outputs/scalyr_integration_spec.rb
- spec/logstash/outputs/scalyr_spec.rb
This pull request implements error specific failed HTTP request retrying.
This change allows us to reduce unnecessary load on the client and the server in situations where it makes no sense to try to retry as fast as possible (e.g. during deploy window or when the client is throttled by the server).
We noticed that during our deploy times when a short unavailability (~30 seconds) is expected when queue servers are getting restarted in a rolling fashion, logstash clients cause a lot of unnecessary load on the backend when they are trying to retry very fast when this happens.
To reduce this load, this pull request implements error type specific request retrying settings and state tracking.
In this PR I introduce new `RetryStateTracker` abstraction which allows us to track and update retry …
> Implement error / exception type specific HTTP request retrying

- .github/workflows/secrets-scanner.yaml
This pull request adds a workflow which uses trufflehog to automatically scan files and commits for secrets on push, PR and as part of a daily cron trigger.
> Add secrets scanning workflow
